### ISSUE TITLE
Not showing properly on tablet

### ISSUE THREAD

**Issue by vcrepin** [flaviocolonna/ion-snackbar#1]
Hello. This plugin is very useful but on my samsung tablet and ipad the snack does not show correctly. The text is not well formatted. Is it supposed to work correctly on tablets ?

**Comment by flaviocolonna** [comment]
Hi! Thanks for interesting on this plugin! Yeah it should work and I tried it with browser emulation. Anyway, how many lines are you trying to display? I will check again on a normal device.

**Comment by vcrepin** [comment]
IT is sometimes 2 Lines. But even with only one IT is not ok. The snack is not full page horizontally and the close buutton is not positioned correctly.

**Comment by vcrepin** [comment]
Hello. Are you planning to look à this problem in the near future ? I have to plan my releases.

Regards.

**Comment by flaviocolonna** [comment]
Hi! Yes, I am sorry. I am going to fix this as soon as possible. When should you need it?
Anyway, this snackbar for tablet must work with just one line. Two lines are not in the Google guidelines. If one line is too long, that will be cut. Furthermore in the tablet the width is not full but almost 80% with 10% margin both sides.
At the end I will check the close button.
I am sorry but I tried to follow the guidelines.

**Comment by vcrepin** [comment]
As soon as possible but i don't want to put pressure on you. I know youre not paid for that. On the phone it behaves like you Say but not on the tablet. IT is about 50℅ width and completely aligned left. And the button appears under the text.

**Comment by flaviocolonna** [comment]
So on the phone is it displaying two lines correctly?
Which tablet are you using?

**Comment by vcrepin** [comment]
I tried on a Samsung and an iPad. Same incorrect result.

**Comment by vcrepin** [comment]
And yes 2 Lines are correct on the phone

**Comment by flaviocolonna** [comment]
is it a web app you are testing on or an hybrid app? Which browser are you using if it is a web app? 

Anyway I have update now the plugin removing the media queries for detecting tablets and inserting userAgent, injecting the correct css.

**Comment by vcrepin** [comment]
IT is an ionic app.

**Comment by vcrepin** [comment]
All right. I'll try it. Thanks!

**Comment by flaviocolonna** [comment]
So actually I have tested it with browser emulation, that should be almost the same, and with every tablet is working. I suggest you to debug your app through chrome inspect and check if there are some other rules in your stylesheet, or ionic css, could break mine. I would like to know why is breaking.

**Comment by vcrepin** [comment]
Well it works. Thank you very much

**Comment by flaviocolonna** [comment]
So is it working properly on tablets? If so, can I close this issue?

**Comment by vcrepin** [comment]
Yes. as expected on ipad and samsung.

**Comment by flaviocolonna** [comment]
Well, if you agree, I would like to know which is your app, maybe giving me the link to the market, in order to create a section showing where the plugin has been installed. It would be great!

**Comment by vcrepin** [comment]
My app is called HunterHelper. You can find it in Google Play (Android) and App Store (IOS)

**Comment by vcrepin** [comment]
https://play.google.com/store/apps/details?id=com.elapsetech.mobile.hunterhelper
